# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9f967a6fe73762f1235f51dba71f3af4eabdde78c7d71587987417276dfbc9c140bde757c78b950e3641ae0d68b56ff1fbcd509e5b5a3c86d8e616514ef96d70

test:
  secret_key_base: 799d1bd9558a5bb62674cfee7ea77278f14633024529dba64aba3a7051e968541f11b2579e4fcdd650e861a4ae0146ab3ff77481f2058063c34e84d394071253

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
